addpath(genpath('/dagher/dagher11/filip/Software/BrainSpace-0.1.2'));
addpath(genpath('/dagher/dagher11/filip/Software/gifti-main'));
addpath(genpath('/dagher/dagher11/filip/Software/netneurotools'));
addpath(genpath('/dagher/dagher11/filip/Software/neuromaps'));


[v_dkt_lh, l_dkt_lh, ct_dkt_lh]=read_annotation('/dagher/dagher11/filip/Obesity_maps/data_old/DKT.annot');

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /dagher/dagher11/filip/Obesity_maps/data/PLS1_ROIscores_BMI_DBM_LH.csv
%
% Auto-generated by MATLAB on 07-Jun-2022 10:39:25

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PLS1ROIscores = readtable("/dagher/dagher11/filip/Obesity_maps/UKBB/PLS1_ROIscores_UKBB_CT_DKT_LHRH.csv", opts);


%% Clear temporary variables
clear opts

%% Merge labels in .annot with data file manually 

PLS1_plot=table(PLS1ROIscores.VarName1,ct_dkt_lh.table([3:4,6:32, 35:36],5));
PLS1_plot.Properties.VariableNames{1} = 'score';
PLS1_plot.Properties.VariableNames{2} = 'number';

%% Deparcellate

vertex_img=[];
unique_values=unique(l_dkt_lh);
unique_values(6)=[]; % remove 'unknown'

for i=1:length(unique(l_dkt_lh))-1
    lab=unique_values(i);
    idx=find(l_dkt_lh==lab);
    vertex_img(idx)=PLS1_plot.score(PLS1_plot.number==lab);
end


%% Plot data

plsroi=plot_hemispheres(vertex_img', {'/dagher/dagher11/filip/Obesity_maps/data_old/lh.white'}, 'views','lmap','labeltext',{'Component 1 loadings'});
hold on
colormap redblue

exportgraphics(gcf,'/dagher/dagher11/filip/Obesity_maps/UKBB/Component_thickness_nsynth.tif','Resolution',300)