%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /dagher/dagher11/filip/Obesity_maps/Final_results/PLS1_catWeights_BMI_DBM_Cammoun_LHRH.csv
%
% Auto-generated by MATLAB on 14-Mar-2023 10:47:42
close all
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["monitoring", "VarName2", "VarName3"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "monitoring", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "monitoring", "EmptyFieldRule", "auto");

% Import the data
PLS1catWeightsBMIDBMCammounLHRH = readtable("/dagher/dagher11/filip/Obesity_maps/UKBB/PLS1_geneWeights_UKBB_CT_DKT_LHRH.csv", opts);
PLS1catWeightsBMIDBMCammounLHRH.Properties.VariableNames = {'Term','Num','Weight'};
pos=PLS1catWeightsBMIDBMCammounLHRH;
neg=PLS1catWeightsBMIDBMCammounLHRH;

%% Clear temporary variables
clear opts

col=redblue(10);

pos((pos.Weight)<3,:)=[];

figure()
wordcloud(pos, 'Term', 'Weight','Color',col(8,:),'HighlightColor',col(10,:))
exportgraphics(gcf,'/dagher/dagher11/filip/Obesity_maps/UKBB/Nsynth_positive_terms.tif','Resolution',300)


figure()
neg((neg.Weight)>-3,:)=[];
neg.Weight=abs(neg.Weight);

wordcloud(neg, 'Term', 'Weight', 'Color',col(3,:), 'HighlightColor',col(2,:))
exportgraphics(gcf,'/dagher/dagher11/filip/Obesity_maps/UKBB/Nsynth_negative_terms.tif','Resolution',300)

