%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /dagher/dagher11/filip/Obesity_maps/data/PLS1_geneWeights_BMI_DBM_LH.csv
%
% Auto-generated by MATLAB on 07-Jun-2022 13:21:21

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Gene", "ID", "BR"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Gene", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Gene", "EmptyFieldRule", "auto");

% Import the data
PLS1geneWeightsBMIDBMLH = readtable("/dagher/dagher11/filip/Obesity_maps/HCPA/PLS1_geneWeights_HCPA_CT_DKT_LH.csv", opts);


%% Clear temporary variables
clear opts

%% Take only sig genes

genes_pos=table(PLS1geneWeightsBMIDBMLH.Gene(PLS1geneWeightsBMIDBMLH.BR>3));
genes_pos.Var1 = convertStringsToChars(genes_pos.Var1);

%% Save as csv

writetable(genes_pos, '/dagher/dagher11/filip/Obesity_maps/HCPA/Sig_genes_PLS1_BMI_positive.txt')

%% Take only sig genes

genes_neg=table(PLS1geneWeightsBMIDBMLH.Gene(PLS1geneWeightsBMIDBMLH.BR<-3));
genes_neg.Var1 = convertStringsToChars(genes_neg.Var1);

%% Save as csv

writetable(genes_neg, '/dagher/dagher11/filip/Obesity_maps/HCPA/Sig_genes_PLS1_BMI_negative.txt')