addpath(genpath('/dagher/dagher11/filip/Software/BrainSpace-0.1.2'));
addpath(genpath('/dagher/dagher11/filip/Software/gifti-main'));
addpath(genpath('/dagher/dagher11/filip/Software/netneurotools'));
addpath(genpath('/dagher/dagher11/filip/Software/neuromaps'));


[v_dkt_lh, l_dkt_lh, ct_dkt_lh]=read_annotation('/home/bic/fmorys/nnt-data/atl-cammoun2012/fsaverage/atl-Cammoun2012_space-fsaverage_res-125_hemi-L_deterministic.annot');
[v_dkt_rh, l_dkt_rh, ct_dkt_rh]=read_annotation('/home/bic/fmorys/nnt-data/atl-cammoun2012/fsaverage/atl-Cammoun2012_space-fsaverage_res-125_hemi-R_deterministic.annot');

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /dagher/dagher11/filip/Obesity_maps/data/PLS1_ROIscores_BMI_DBM_LH.csv
%
% Auto-generated by MATLAB on 07-Jun-2022 10:39:25

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PLS1ROIscoresBMIDBMLH = readtable("/dagher/dagher11/filip/Obesity_maps/Final_results/PLS1_ROIscores_BMI_DBM_Cammoun_LHRH.csv", opts);


%% Clear temporary variables
clear opts

%% Merge labels in .annot with data file manually 

PLS1_plot_LH=table(PLS1ROIscoresBMIDBMLH.VarName1(116:226),ct_dkt_lh.table([2:4 6:113],5));
PLS1_plot_LH.Properties.VariableNames{1} = 'score';
PLS1_plot_LH.Properties.VariableNames{2} = 'number';


PLS1_plot_RH=table(PLS1ROIscoresBMIDBMLH.VarName1(1:108),ct_dkt_rh.table([2:4 6:110],5));
PLS1_plot_RH.Properties.VariableNames{1} = 'score';
PLS1_plot_RH.Properties.VariableNames{2} = 'number';

%% Deparcellate

vertex_img_lh=[];
unique_values=unique(l_dkt_lh);
%unique_values(6)=[]; % remove 'unknown'

for i=1:length(unique(l_dkt_lh))-1
    if i==18 | i==25 % CC and unknown
        continue
    end
    lab=unique_values(i);
    idx=find(l_dkt_lh==lab);
    vertex_img_lh(idx)=PLS1_plot_LH.score(PLS1_plot_LH.number==lab);
end

%% Deparcellate for RH

vertex_img_rh=[];
unique_values=unique(l_dkt_rh);
%unique_values(6)=[]; % remove 'unknown'

for i=1:length(unique(l_dkt_rh))-1
    if i==16 | i==21 % CC and unknown
        continue
    end
    lab=unique_values(i);
    idx=find(l_dkt_rh==lab);
    vertex_img_rh(idx)=PLS1_plot_RH.score(PLS1_plot_RH.number==lab);
end

%% Plot data

plsroi=plot_hemispheres([vertex_img_rh'; vertex_img_lh'], {'/dagher/dagher11/filip/Obesity_maps/data/lh.white', '/dagher/dagher11/filip/Obesity_maps/data/rh.white'}, 'views','lmap','labeltext',{'Component 1 scores'});
hold on
colormap parula %redblue

exportgraphics(gcf,'Component1_nsynth.tif','Resolution',300)



