%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /dagher/dagher11/filip/Obesity_maps/data/GWAS_genes_map_Yengo.csv
%
% Auto-generated by MATLAB on 31-Oct-2022 11:25:49

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "e04";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
GWASgenesmapYengo = readtable("/dagher/dagher11/filip/Obesity_maps/data/GWAS_genes_map_Yengo.csv", opts);

%% Convert to output type
GWASgenesmapYengo = table2array(GWASgenesmapYengo);

%% Clear temporary variables
clear opts

GWASgenesmapYengo(GWASgenesmapYengo==0)=mean(GWASgenesmapYengo);

plot_hemispheres(GWASgenesmapYengo/1000, {'/dagher/dagher11/filip/Obesity_maps/data/lh.white'}, 'views','lmap','labeltext',{'BMI - genes',});

exportgraphics(gcf,'Yengo_map.tif','Resolution',300)
